### ISSUE TITLE
nil values on destroy result in errors reported

### ISSUE THREAD

**Issue by mengesb** [terraform-google-modules/terraform-google-project-factory#248]
Unfortunately, Terraform reports `nil` value returns as an error, and there should be a way to default these or handle it more gracefully.

On destroy:
```text
Error: Error applying plan:

9 errors occurred:
	* module.project.module.project-factory.output.service_account_display_name: variable "default_service_account" is nil, but no error was reported
	* module.project.module.project-factory.output.project_number: variable "main" is nil, but no error was reported
	* module.project.module.project-factory.output.project_id: variable "main" is nil, but no error was reported
	* module.project.module.project-factory.output.project_name: variable "main" is nil, but no error was reported
	* module.project.module.project-factory.output.service_account_email: variable "default_service_account" is nil, but no error was reported
	* module.project.module.project-factory.output.service_account_id: variable "default_service_account" is nil, but no error was reported
	* module.project.module.project-factory.output.service_account_name: variable "default_service_account" is nil, but no error was reported
	* module.project.module.project-factory.output.service_account_unique_id: variable "default_service_account" is nil, but no error was reported



Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Ideally these should return cleanly on destroy.

**Comment by ingwarr** [comment]
@mengesb Could you please provide me with steps to reproduce and versions of terraform, providers, variables, etc.

**Comment by thefirstofthe300** [comment]
I'm 99% certain that @mengesb's issue is [this upstream issue](https://github.com/hashicorp/terraform/issues/17862).

**Comment by nick4fake** [comment]
@mengesb I am sorry, but we have failed to reproduce it. Could you please share your config?

**Comment by mengesb** [comment]
Sorry for the long gap in reply time... I only just now noticed responses.

There's really nothing special about my config; and I think @thefirstofthe300 might be correct, however at last recollection we should be using 0.11.14 and I thought that should have been resolved.

```hcl
module "project" {
  source                  = "terraform-google-modules/project-factory/google"
  version                 = "2.4.1"
  org_id                  = "${var.google["org"]}"
  folder_id               = "${var.google["folder"]}"
  name                    = "${var.project}"
  random_project_id       = "false"
  project_id              = "${var.project}"
  billing_account         = "${var.google["billing"]}"
  credentials_path        = "${local_file.credentials.filename}"
  default_service_account = "${var.google["service"]}"
  activate_apis           = "${var.google_apis}"
  shared_vpc              = "${var.host_project}"
  shared_vpc_subnets      = "${var.subnets}"
  auto_create_network     = "${var.auto_create_network}"
  labels                  = "${local.common_labels}"
}
```

The only real difference is that using a `local_file` resource to provide the `credentials_path` variable the path to a file ... this is because I use a map to store the credentials information which is compatible with `jsonencode()` to configure the provider... but your code is hard-coded for a `file()` interpolation

**Comment by morgante** [comment]
@mengesb We're no longer supporting Terraform 0.11 for this module so I'm going to close this for now.

If you upgrade to 0.12 and this is still happening, please reopen. Thanks!
